# Numerical types

integer

float

complex numbers

Booleans



# Containers
list

strings

dictionary

tuples

# Control Flow
if  elif else

for range

In [1]:
a = 6
if a==2:
    print('YES')
elif a == 3:
    print('NO')
elif a ==5:
    pass
else:
    print('MAYBE')

MAYBE


In [2]:
for i in range(4,9):
    print(i)
    
print('-----')

4
5
6
7
8
-----


In [3]:
for i in range(0,10,3):
    print(i)
    
print('-----')

0
3
6
9
-----


In [4]:
list=['a','b','c','d','e','f']
list2 = ['aa','bb','cc','dd','ee','ff']
for i,j in enumerate(list):
    print(i,j,list2[i])

0 a aa
1 b bb
2 c cc
3 d dd
4 e ee
5 f ff


In [5]:
n=20
i=1
while i<n:
    print(i)
    i=i+5

1
6
11
16


I'm doing a serius bl bla bla

In [6]:
n=20
i=2
while i<n:
    print(i)
    if i == 15:
        break
    i=i+2

2
4
6
8
10
12
14
16
18


In [7]:
i=1
j = (4 * i**2) / (4 *i**2 - 1)
for i in range(2,1000000):
    j = j * (4 * i**2) / (4 *i**2 - 1)

print(2*j)

3.141591868191682


In [8]:
a = False
b = False
c = True
print(a & b)
print(a | b)
print(a^c)

False
False
True


In [9]:
print(0b0001 & 0b0011)
print(1 & 3)
a = 60
b =13
print(a&b)
print("0b{0:08b}".format(a))
print("0b{0:08b}".format(b))
print("0b{0:08b}".format(a&b))
print("0b{0:08b}".format(12))

1
1
12
0b00111100
0b00001101
0b00001100
0b00001100


# Packages in Python 
Most of the power of a programming language is in its packages. General tools are built into Python, specialized tools built up from these basic units live in packages that can be called upon when needed. You can think of a package as a collection of files (called modules) that contains functions for use by other programs. Note the term library is simply a generic term for a bunch of code that was designed with the aim of being usable by many applications. Often Python packages are called Python libraries. Very complex packages like NumPy have hundreds of individual modules so putting them into a directory-like structure keeps things organized and avoids name collisions. A program must import a package module before using it. Then refer to things from the module as module_name.thing_name. Python uses . to mean “part of”. The ”dot notation” is used to call a specific module inside package.

This can be accomplished by 'importing' the desired library.

Common libraries
* numpy
* os
* system
* matplotlib
* scipy
* astropy

In [10]:
import numpy as np

In [11]:
a = np.array([1,2,3,4,5])
a.std()

np.float64(1.4142135623730951)

# end of lecture 4

In [12]:
a = np.array([1,2,3,4,5])
print(a**2)
print(a+a)
print(a*10)

[ 1  4  9 16 25]
[ 2  4  6  8 10]
[10 20 30 40 50]


# Arrays

Like Python lists, numpy arrays are also composed of ordered values and also use indexing.
Unlike lists which do not require a specific Python package to be defined (or worked with), NumPy arrays are defined using the ``array()`` function from the numpy package, which we imported earlier.

A key characteristic of NumPy arrays is that all elements in the array must be the same type of data (i.e. all integers, floats, strings, etc).
This allows us to apply mathematical operations to each value in an array.

**Exercise:** <font color=blue>Let's see this in action. We will do the following:</font>
- <font color=blue>Multiply all elements in the array by 2</font>
- <font color=blue>Compute the mean of the array</font>
- <font color=blue>Compute the standard deviation</font>
- <font color=blue>Sum all elements in the array</font>

In [13]:
odds = [1,3,5,7] 
myarray = np.array(odds)

print(myarray*2)
arraymean = np.mean(myarray)  # compute the mean
arraystd = np.std(myarray)  # compute the standard deviation
arraysum = np.sum(myarray)  # compute the sum of the array
print(arraymean,arraystd,arraysum)

[ 2  6 10 14]
4.0 2.23606797749979 16


# 2D Arrays

We can also have 2D arrays. We will use them a lot when working with astronomical images. Now that we have two dimensions, we must use 2 slices separated by a ``,`` to select elements using the format ``myarray[slice_row,slice_column]``.

**Example:** <font color=blue>Let's define the 3x4 (3 rows, 4 columns) array and do the following operations:</font>
- <font color=blue>View the full array</font>
- <font color=blue>View its shape</font> np.shape(...)
- <font color=blue>Print the first entry of the second row</font>
- <font color=blue>Print the entire first row</font>
- <font color=blue>Print the first two elements for each of the last two rows</font> extra credit....

In [14]:
data = np.array(((1,2,3,4),(5,6,7,8),(9,10,11,12)))

print(data)
print(np.shape(data))
print(data[1,0])
print(data[0,:])
print(data[-2:,:2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
5
[1 2 3 4]
[[ 5  6]
 [ 9 10]]


In [15]:
data.mean(1)

array([ 2.5,  6.5, 10.5])